image: "python:3.10"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install -U pip setuptools
  - pip install pytest pytest-cov codecov sphinx sybil tqdm
  - pip install -e .

pytest:
  stage: test
  parallel:
    matrix:
      - IMAGE: ['python:3.6', 'python:3.10']
  image: $IMAGE
  script:
    - pytest --cov=progress_passthrough
  artifacts:
    paths:
      - .coveragerc

upload_coverage:
  stage: deploy
  rules:
    # only run this on main so we can keep the upload token protected
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov

pages:
  stage: deploy
  script:
    - (cd doc && make html); mv doc/_build/html public
  artifacts:
    paths:
      - public
  only:
    - main
